# 业务侧 prj 增量：与 framework/prj.conf 一起传给 west/cmake（见 README）
CONFIG_ZEPHYR_GATEWAY_BUSINESS=y

# 关闭框架中的所有示例模块
CONFIG_EXAMPLE_MODULE_A_ENABLE=n
CONFIG_EXAMPLE_MODULE_B_ENABLE=n
CONFIG_THREAD_IPC_SERVICE_EXAMPLE=n
